using Content.Shared._AU14.Callsigns;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._AU14.Callsigns;

[GenerateTypedNameReferences]
public sealed partial class AU14CallsignConsoleWindow : DefaultWindow
{
    public event Action<NetEntity?, string>? OnRenameElement;
    public event Action<NetEntity, string>? OnSetSuffix;

    private static readonly Color Accent = Color.FromHex("#6BC7FF");
    private static readonly Color TextBright = Color.FromHex("#C7D7EA");
    private static readonly Color TextDim = Color.FromHex("#9DB5D1");
    private static readonly Color PanelBg = Color.FromHex("#0B131F");
    private static readonly Color PanelBorder = Color.FromHex("#1E3450");

    private bool _canEdit;

    public AU14CallsignConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        Title = Loc.GetString("au14-callsign-console-title");
    }

    public void UpdateState(AU14CallsignConsoleState state, bool canEdit)
    {
        _canEdit = canEdit;

        FactionLabel.Text = Loc.GetString("au14-callsign-console-net", ("faction", state.Faction.ToUpperInvariant()));
        EditModeLabel.Text = canEdit
            ? Loc.GetString("au14-callsign-console-mode-edit")
            : Loc.GetString("au14-callsign-console-mode-readonly");
        EditModeLabel.FontColorOverride = canEdit ? Accent : TextDim;

        var stations = 0;

        ElementList.RemoveAllChildren();

        foreach (var element in state.Elements)
        {
            stations += element.Rows.Count;
            ElementList.AddChild(BuildElementPanel(element));
        }

        EntryCountLabel.Text = Loc.GetString("au14-callsign-console-stations", ("count", stations));
    }

    private Control BuildElementPanel(AU14CallsignConsoleElement element)
    {
        var panel = new PanelContainer
        {
            HorizontalExpand = true,
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = PanelBg,
                BorderColor = PanelBorder,
                BorderThickness = new Thickness(1),
            },
        };

        var body = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(10, 8),
            SeparationOverride = 4,
            HorizontalExpand = true,
        };

        // Header: element word + label, and a rename control for editors.
        var header = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 8,
            HorizontalExpand = true,
        };

        header.AddChild(new Label
        {
            Text = element.Word,
            FontColorOverride = Accent,
            MinWidth = 120,
        });

        header.AddChild(new Label
        {
            Text = element.Label,
            FontColorOverride = TextDim,
            HorizontalExpand = true,
        });

        if (_canEdit)
        {
            var renameEdit = new LineEdit
            {
                PlaceHolder = Loc.GetString("au14-callsign-console-rename-placeholder"),
                MinWidth = 120,
            };

            var renameButton = new Button
            {
                Text = Loc.GetString("au14-callsign-console-set-button"),
                MinWidth = 48,
            };

            var squad = element.Squad;

            renameButton.OnPressed += _ =>
            {
                var word = renameEdit.Text.Trim();

                if (word.Length == 0)
                    return;

                OnRenameElement?.Invoke(squad, word);
                renameEdit.Text = string.Empty;
            };

            header.AddChild(renameEdit);
            header.AddChild(renameButton);
        }

        body.AddChild(header);

        if (element.Rows.Count == 0)
        {
            body.AddChild(new Label
            {
                Text = Loc.GetString("au14-callsign-console-no-stations"),
                FontColorOverride = TextDim,
            });
        }

        foreach (var row in element.Rows)
        {
            body.AddChild(BuildMemberRow(row));
        }

        panel.AddChild(body);
        return panel;
    }

    private Control BuildMemberRow(AU14CallsignConsoleRow row)
    {
        var line = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 8,
            HorizontalExpand = true,
        };

        line.AddChild(new Label
        {
            Text = row.Callsign,
            FontColorOverride = Accent,
            MinWidth = 140,
            ClipText = true,
        });

        line.AddChild(new Label
        {
            Text = row.Name,
            FontColorOverride = TextBright,
            HorizontalExpand = true,
            ClipText = true,
        });

        line.AddChild(new Label
        {
            Text = row.Job,
            FontColorOverride = TextDim,
            MinWidth = 140,
            ClipText = true,
        });

        if (_canEdit)
        {
            var suffixEdit = new LineEdit
            {
                PlaceHolder = Loc.GetString("au14-callsign-console-suffix-placeholder"),
                MinWidth = 70,
            };

            var suffixButton = new Button
            {
                Text = Loc.GetString("au14-callsign-console-set-button"),
                MinWidth = 48,
            };

            var member = row.Member;

            suffixButton.OnPressed += _ =>
            {
                var suffix = suffixEdit.Text.Trim();

                if (suffix.Length == 0)
                    return;

                OnSetSuffix?.Invoke(member, suffix);
                suffixEdit.Text = string.Empty;
            };

            line.AddChild(suffixEdit);
            line.AddChild(suffixButton);
        }

        return line;
    }
}
