using System.Linq;
using Content.Shared._AU14.Radio;
using Content.Shared.Radio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;

namespace Content.Client._AU14.Radio;

[GenerateTypedNameReferences]
public sealed partial class ANPRCRadioWindow : DefaultWindow
{
    [Dependency] private IPrototypeManager _prototype = default!;

    public event Action<int>? OnSelectSlot;
    public event Action? OnTogglePower;
    public event Action? OnToggleMonitor;
    public event Action<RadioMode>? OnSetMode;
    public event Action<bool>? OnSetScan;
    public event Action<RadioTxPower>? OnSetTxPower;
    public event Action<int>? OnSetSquelch;
    public event Action<string>? OnSetCallsign;
    public event Action<string>? OnAddSlot;
    public event Action<int>? OnDeleteSlot;
    public event Action<int, ProtoId<RadioChannelPrototype>>? OnSetSlotChannel;
    public event Action<int>? OnClearSlot;
    public event Action? OnCryptoZeroize;
    public event Action? OnCryptoDestroy;
    public event Action? OnCryptoRecrypto;
    public event Action? OnRadioCheck;
    public event Action<int, string>? OnManualFrequency;

    private static readonly Color LcdBright = Color.FromHex("#3FCF8E");
    private static readonly Color LcdMid = Color.FromHex("#2D9E60");
    private static readonly Color LcdDim = Color.FromHex("#4A7A55");
    private static readonly Color LcdOff = Color.FromHex("#1E4A2E");
    private static readonly Color LcdWarning = Color.FromHex("#D6B85A");

    private static readonly Color TextBright = Color.FromHex("#C8D2E8");
    private static readonly Color TextDim = Color.FromHex("#687A9A");
    private static readonly Color TextGood = Color.FromHex("#78D69B");
    private static readonly Color TextWarn = Color.FromHex("#D6B85A");
    private static readonly Color TextBad = Color.FromHex("#D65A5A");
    private static readonly Color TextLog = Color.FromHex("#3FCF8E");

    private ANPRCRadioState? _lastState;

    private int _entryTargetSlot = -1;

    private enum EntryTab { Freq, Net }
    private EntryTab _activeEntryTab = EntryTab.Freq;

    private string? _netLogChannelFilter;
    private string _netLogSearchFilter = string.Empty;
    private readonly List<string> _netLogChannels = new();

    private readonly List<string> _callsignPresets = new();

    public ANPRCRadioWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Title = Loc.GetString("anprc-window-title");

        // Footer
        PowerButton.OnPressed += _ => OnTogglePower?.Invoke();

        // Controls
        ModeButton.OnPressed += _ =>
        {
            if (_lastState == null) return;
            var next = _lastState.Mode switch
            {
                RadioMode.FrequencyHopping => RadioMode.SingleChannel,
                RadioMode.SingleChannel    => RadioMode.CipherText,
                RadioMode.CipherText       => RadioMode.PlainText,
                RadioMode.PlainText        => RadioMode.FrequencyHopping,
                _                          => RadioMode.FrequencyHopping,
            };
            OnSetMode?.Invoke(next);
        };

        MonitorButton.OnPressed += _ => OnToggleMonitor?.Invoke();

        ScanButton.OnPressed += _ =>
        {
            if (_lastState == null) return;
            OnSetScan?.Invoke(!_lastState.ScanEnabled);
        };

        SquelchButton.OnPressed += _ =>
        {
            if (_lastState == null) return;
            var next = _lastState.SquelchLevel >= ANPRCRadioComponent.MaxSquelchLevel ? 0 : _lastState.SquelchLevel + 1;
            OnSetSquelch?.Invoke(next);
        };

        TxPowerButton.OnPressed += _ =>
        {
            if (_lastState == null) return;
            var next = _lastState.TxPower switch
            {
                RadioTxPower.Low    => RadioTxPower.Medium,
                RadioTxPower.Medium => RadioTxPower.High,
                _                   => RadioTxPower.Low,
            };
            OnSetTxPower?.Invoke(next);
        };

        // Callsign
        CallsignSetButton.OnPressed += _ =>
        {
            var text = CallsignLineEdit.Text.Trim().ToUpperInvariant();
            if (text.Length > ANPRCRadioComponent.MaxCallsignLength)
                text = text[..ANPRCRadioComponent.MaxCallsignLength];
            OnSetCallsign?.Invoke(text);
            CallsignLineEdit.Text = string.Empty;
        };

        // Picking a preset fills the line edit; SET still confirms, and the
        // field stays free-text for custom callsigns.
        CallsignPresetButton.OnItemSelected += args =>
        {
            CallsignPresetButton.SelectId(0);

            if (args.Id <= 0 || args.Id > _callsignPresets.Count)
                return;

            CallsignLineEdit.Text = _callsignPresets[args.Id - 1];
        };

        // Add slot panel
        AddSlotButton.OnPressed += _ =>
        {
            AddSlotPanel.Visible = true;
            AddSlotLabelEdit.Text = string.Empty;
            AddSlotLabelEdit.GrabKeyboardFocus();
        };

        AddSlotConfirmButton.OnPressed += _ =>
        {
            var label = AddSlotLabelEdit.Text.Trim().ToUpperInvariant();
            if (label.Length > ANPRCRadioComponent.MaxLabelLength)
                label = label[..ANPRCRadioComponent.MaxLabelLength];
            if (string.IsNullOrWhiteSpace(label)) label = "NET";
            OnAddSlot?.Invoke(label);
            AddSlotPanel.Visible = false;
            AddSlotLabelEdit.Text = string.Empty;
        };

        AddSlotCancelButton.OnPressed += _ =>
        {
            AddSlotPanel.Visible = false;
            AddSlotLabelEdit.Text = string.Empty;
        };

        // Slot entry panel
        EntryTabFreqButton.OnPressed += _ => ShowEntryTab(EntryTab.Freq);
        EntryTabNetButton.OnPressed  += _ => ShowEntryTab(EntryTab.Net);

        EntryTabClearButton.OnPressed += _ =>
        {
            if (_entryTargetSlot < 0) return;
            OnClearSlot?.Invoke(_entryTargetSlot);
            CloseSlotEntryPanel();
        };

        EntryFreqConfirmButton.OnPressed += _ =>
        {
            if (_entryTargetSlot < 0) return;
            var text = EntryFreqLineEdit.Text.Trim();
            if (!string.IsNullOrEmpty(text))
                OnManualFrequency?.Invoke(_entryTargetSlot, text);
            CloseSlotEntryPanel();
        };

        SlotEntryCloseButton.OnPressed += _ => CloseSlotEntryPanel();

        // COMSEC
        ZeroizeButton.OnPressed  += _ => OnCryptoZeroize?.Invoke();
        DestroyButton.OnPressed  += _ => OnCryptoDestroy?.Invoke();
        RecryptoButton.OnPressed += _ => OnCryptoRecrypto?.Invoke();

        // Radio check
        RadioCheckButton.OnPressed += _ => OnRadioCheck?.Invoke();

        // Net log filters
        NetLogChannelFilter.OnItemSelected += args =>
        {
            NetLogChannelFilter.SelectId(args.Id);
            _netLogChannelFilter = args.Id == 0 ? null : _netLogChannels[args.Id - 1];
            if (_lastState != null)
                RebuildNetLog(_lastState);
        };

        NetLogSearchEdit.OnTextChanged += args =>
        {
            _netLogSearchFilter = args.Text.Trim();
            if (_lastState != null)
                RebuildNetLog(_lastState);
        };

        NetLogFilterClearButton.OnPressed += _ =>
        {
            _netLogChannelFilter = null;
            _netLogSearchFilter  = string.Empty;
            NetLogSearchEdit.Text = string.Empty;
            NetLogChannelFilter.SelectId(0);
            if (_lastState != null)
                RebuildNetLog(_lastState);
        };

        // Initially hide overlay panels
        AddSlotPanel.Visible   = false;
        SlotEntryPanel.Visible = false;
    }

    // State update

    public void UpdateState(ANPRCRadioState state)
    {
        _lastState = state;

        var hasActiveDynFreq = state.FrequencyOverrides.TryGetValue(state.ActiveSlot, out var activeDynFreq);
        var hasActiveChannel = !hasActiveDynFreq &&
                               state.Presets.TryGetValue(state.ActiveSlot, out var activeChannel) &&
                               _prototype.TryIndex(activeChannel, out var activeProto);
        // Re-read for use below
        state.Presets.TryGetValue(state.ActiveSlot, out var activeChannelId);
        RadioChannelPrototype? activeProto2 = null;
        if (hasActiveChannel && !string.IsNullOrEmpty(activeChannelId.Id))
            _prototype.TryIndex(activeChannelId, out activeProto2);

        var hasAnyActive = hasActiveChannel || hasActiveDynFreq;
        // A planted retrans station is fully operable from its panel despite not being worn.
        var deployed = state.IsEquipped || state.Planted;
        var online = state.Enabled && deployed;
        var ready  = online && hasAnyActive && state.ActiveSlot >= 0;

        // Header
        HeaderPowerLabel.Text              = state.Enabled ? "PWR: ON" : "PWR: OFF";
        HeaderPowerLabel.FontColorOverride = state.Enabled ? TextGood  : TextBad;

        if (state.Planted)
        {
            HeaderLinkLabel.Text              = "LINK: RETRANS";
            HeaderLinkLabel.FontColorOverride = state.Enabled ? TextGood : TextDim;
        }
        else if (!state.IsEquipped)
        {
            HeaderLinkLabel.Text              = "LINK: NOT WORN";
            HeaderLinkLabel.FontColorOverride = TextWarn;
        }
        else if (!state.Enabled)
        {
            HeaderLinkLabel.Text              = "LINK: STBY";
            HeaderLinkLabel.FontColorOverride = TextDim;
        }
        else
        {
            HeaderLinkLabel.Text              = hasAnyActive ? "LINK: READY" : "LINK: NO NET";
            HeaderLinkLabel.FontColorOverride = hasAnyActive ? TextGood      : TextWarn;
        }

        // LCD
        LcdModeLabel.Text              = $"MODE: {ModeShort(state.Mode)}";
        LcdModeLabel.FontColorOverride = online ? LcdDim : LcdOff;
        CryptoLabel.FontColorOverride  = online ? LcdDim : LcdOff;

        if (hasActiveDynFreq)
        {
            var fStr = FormatFreq(activeDynFreq);
            FrequencyLabel.Text   = fStr;
            ChannelNameLabel.Text = "DIRECT FREQ";
            ChannelIdLabel.Text   = $"FREQ: {fStr}";
            BandLabel.Text        = $"BAND: {BandName(activeDynFreq)}";
            WaveformLabel.Text    = "WF: LOS";

            FrequencyLabel.FontColorOverride   = ready ? LcdBright : LcdOff;
            ChannelNameLabel.FontColorOverride = ready ? LcdMid    : LcdOff;
            ChannelIdLabel.FontColorOverride   = online ? LcdDim   : LcdOff;
            BandLabel.FontColorOverride        = online ? LcdDim   : LcdOff;
            WaveformLabel.FontColorOverride    = online ? LcdDim   : LcdOff;
        }
        else if (hasActiveChannel && activeProto2 != null)
        {
            FrequencyLabel.Text   = FormatFreq(activeProto2.Frequency);
            ChannelNameLabel.Text = activeProto2.LocalizedName.ToUpperInvariant();
            ChannelIdLabel.Text   = $"CH: {activeChannelId.Id}";
            BandLabel.Text        = $"BAND: {BandName(activeProto2.Frequency)}";
            WaveformLabel.Text    = $"WF: {(activeProto2.LongRange ? "SAT" : "LOS")}";

            FrequencyLabel.FontColorOverride   = ready ? LcdBright : LcdOff;
            ChannelNameLabel.FontColorOverride = ready ? LcdMid    : LcdOff;
            ChannelIdLabel.FontColorOverride   = online ? LcdDim   : LcdOff;
            BandLabel.FontColorOverride        = online ? LcdDim   : LcdOff;
            WaveformLabel.FontColorOverride    = online ? LcdDim   : LcdOff;
        }
        else
        {
            FrequencyLabel.Text   = "-- . ---";
            ChannelNameLabel.Text = state.ActiveSlot < 0 ? "NO SLOT ACTIVE" : "SLOT EMPTY";
            ChannelIdLabel.Text   = "CH: ---";
            BandLabel.Text        = "BAND: ---";
            WaveformLabel.Text    = "WF: ---";

            FrequencyLabel.FontColorOverride   = LcdOff;
            ChannelNameLabel.FontColorOverride = LcdOff;
            ChannelIdLabel.FontColorOverride   = LcdOff;
            BandLabel.FontColorOverride        = LcdOff;
            WaveformLabel.FontColorOverride    = LcdOff;
        }

        if (!online)
        {
            TxIndicator.FontColorOverride = LcdOff;
            TxLabel.Text                  = "OFF";
            TxLabel.FontColorOverride     = LcdOff;
        }
        else if (!hasAnyActive)
        {
            TxIndicator.FontColorOverride = LcdWarning;
            TxLabel.Text                  = "NO NET";
            TxLabel.FontColorOverride     = LcdWarning;
        }
        else
        {
            TxIndicator.FontColorOverride = LcdBright;
            TxLabel.Text                  = state.MonitorEnabled ? "MON" : "STBY";
            TxLabel.FontColorOverride     = state.MonitorEnabled ? LcdBright : LcdDim;
        }

        if (!deployed)
        {
            BitStatusLabel.Text              = "BIT: NOT SEATED";
            BitStatusLabel.FontColorOverride = LcdWarning;
        }
        else if (!state.Enabled)
        {
            BitStatusLabel.Text              = "BIT: OFFLINE";
            BitStatusLabel.FontColorOverride = LcdOff;
        }
        else if (!hasAnyActive)
        {
            BitStatusLabel.Text              = "BIT: NO NET";
            BitStatusLabel.FontColorOverride = LcdWarning;
        }
        else
        {
            BitStatusLabel.Text              = "BIT: PASS";
            BitStatusLabel.FontColorOverride = LcdBright;
        }

        SignalBarsLabel.Text              = Bars(ready ? 8 : 0, 8);
        SignalBarsLabel.FontColorOverride = ready ? LcdBright : LcdOff;

        var batteryFilled = state.HasBattery ? (int)Math.Round(state.BatteryFraction * 6) : 0;
        BatteryBarsLabel.Text              = state.HasBattery ? Bars(batteryFilled, 6) : "NO CELL";
        BatteryBarsLabel.FontColorOverride = !state.HasBattery ? TextBad
                                            : state.BatteryFraction <= 0.2f ? LcdWarning
                                            : LcdDim;

        AntennaLabel.Text              = $"ANT: {state.AntennaLabel}";
        AntennaLabel.FontColorOverride = online ? LcdDim : LcdOff;

        if (!deployed)
        {
            FaultLabel.Text              = "FAULT: NOT WORN";
            FaultLabel.FontColorOverride = TextWarn;
        }
        else if (!state.Enabled)
        {
            FaultLabel.Text              = "FAULT: OFF";
            FaultLabel.FontColorOverride = TextDim;
        }
        else if (!hasAnyActive)
        {
            FaultLabel.Text              = "FAULT: NO NET";
            FaultLabel.FontColorOverride = TextWarn;
        }
        else
        {
            FaultLabel.Text              = "FAULT: NONE";
            FaultLabel.FontColorOverride = TextGood;
        }

        // Callsign: manual station override > wearer's assigned callsign (AUTO)
        if (!string.IsNullOrEmpty(state.Callsign))
        {
            CallsignDisplayLabel.Text              = state.Callsign;
            CallsignDisplayLabel.FontColorOverride = TextGood;
        }
        else if (!string.IsNullOrEmpty(state.WearerCallsign))
        {
            CallsignDisplayLabel.Text              = $"{state.WearerCallsign} (AUTO)";
            CallsignDisplayLabel.FontColorOverride = TextGood;
        }
        else
        {
            CallsignDisplayLabel.Text              = "UNKNOWN STATION";
            CallsignDisplayLabel.FontColorOverride = TextDim;
        }

        RebuildCallsignPresets(state);

        // Slot list (dynamic rows)
        RebuildSlotList(state);

        var slotCount = state.SlotLabels.Count;
        PresetSummaryLabel.Text              = $"{slotCount}/{ANPRCRadioComponent.MaxSlots}";
        PresetSummaryLabel.FontColorOverride = slotCount > 0 ? TextDim : TextWarn;
        AddSlotButton.Disabled               = slotCount >= ANPRCRadioComponent.MaxSlots || !online;

        // Controls
        ModeButton.Text    = $"MODE {ModeShort(state.Mode)}";
        MonitorButton.Text = state.MonitorEnabled ? "MON ON"  : "MON OFF";
        ScanButton.Text    = state.ScanEnabled     ? "SCAN ON" : "SCAN OFF";
        SquelchButton.Text = $"SQL {state.SquelchLevel}";
        TxPowerButton.Text = $"TX {state.TxPower.Short()}";

        ModeButton.Disabled    = !online;
        MonitorButton.Disabled = !online;
        ScanButton.Disabled    = !online;
        SquelchButton.Disabled = !online;
        TxPowerButton.Disabled = !online;
        MonitorButton.Pressed  = state.MonitorEnabled && online;
        ScanButton.Pressed     = state.ScanEnabled && online;

        RoleValueLabel.Text = state.Planted ? "RETRANS STATION" : "RTO RELAY";

        RelayValueLabel.Text              = online && hasAnyActive ? "ANCHOR" : "STBY";
        RelayValueLabel.FontColorOverride = online && hasAnyActive ? TextGood : TextDim;

        DiagnosticLineA.Text              = online && hasAnyActive ? "ANCHOR: ACTIVE"
                                          : online                 ? "ANCHOR: STBY"
                                                                   : "ANCHOR: OFFLINE";
        DiagnosticLineA.FontColorOverride = online && hasAnyActive ? TextGood : TextDim;
        DiagnosticLineB.Text              = online && hasAnyActive ? "BYPASS: ARMED" : "BYPASS: NO";
        DiagnosticLineB.FontColorOverride = online && hasAnyActive ? TextGood : TextDim;

        RoleValueLabel.FontColorOverride = online ? TextBright : TextDim;

        // COMSEC
        var hasFill = !string.IsNullOrEmpty(state.CryptoFaction);
        var secured = hasFill && !state.CryptoStale;

        CryptoStatusLabel.Text              = secured ? $"SECURED ({state.CryptoDesignation})"
                                             : hasFill ? $"STALE ({state.CryptoDesignation})"
                                                        : "UNSECURED";
        CryptoStatusLabel.FontColorOverride = secured ? TextGood : hasFill ? TextWarn : TextBad;

        CryptoFillLabel.Text = hasFill
            ? state.CryptoStale
                ? $"FILL: {state.CryptoDesignation} ({state.CryptoFaction.ToUpperInvariant()}) — SUPERSEDED, RECRYPTO REQUIRED"
                : $"FILL: {state.CryptoDesignation} ({state.CryptoFaction.ToUpperInvariant()})"
            : "FILL: NONE — insert fill card to load";
        CryptoFillLabel.FontColorOverride = secured ? TextGood : hasFill ? TextWarn : TextDim;

        ZeroizeButton.Disabled  = !online || !hasFill;
        DestroyButton.Disabled  = !online || !hasFill;
        RecryptoButton.Disabled = !online || !secured;

        RadioCheckButton.Disabled = !ready;

        // Net log
        RebuildNetLog(state);

        // Footer
        PowerButton.Text = state.Enabled
            ? Loc.GetString("anprc-power-off-button")
            : Loc.GetString("anprc-power-on-button");

        var net = hasActiveDynFreq
            ? $"DIRECT {FormatFreq(activeDynFreq)}"
            : hasActiveChannel && activeProto2 != null
                ? activeProto2.LocalizedName
                : "No net";

        StatusLabel.Text =
            $"{(state.Planted ? "PLANTED" : state.IsEquipped ? "EQUIPPED" : "UNEQUIPPED")}" +
            $" · {(state.Enabled ? "ON" : "OFF")}" +
            $" · {net}";
    }

    /// <summary>
    /// Keeps the preset dropdown in sync with the radio's callsign pool.
    /// Items are only rebuilt when the pool changes, so an open dropdown isn't
    /// yanked shut by the periodic state updates.
    /// </summary>
    private void RebuildCallsignPresets(ANPRCRadioState state)
    {
        if (state.CallsignPresets.SequenceEqual(_callsignPresets))
        {
            CallsignPresetButton.Visible = _callsignPresets.Count > 0;
            return;
        }

        _callsignPresets.Clear();
        _callsignPresets.AddRange(state.CallsignPresets);

        CallsignPresetButton.Clear();
        CallsignPresetButton.AddItem("PRESETS", 0);
        for (var i = 0; i < _callsignPresets.Count; i++)
        {
            CallsignPresetButton.AddItem(_callsignPresets[i], i + 1);
        }

        CallsignPresetButton.SelectId(0);
        CallsignPresetButton.Visible = _callsignPresets.Count > 0;
    }

    // Dynamic slot list

    private void RebuildSlotList(ANPRCRadioState state)
    {
        SlotListContainer.RemoveAllChildren();

        var online = state.Enabled && state.IsEquipped;
        var sortedSlots = state.SlotLabels.Keys.OrderBy(k => k).ToList();

        foreach (var slot in sortedSlots)
        {
            var label  = state.SlotLabels[slot];
            var isActive = slot == state.ActiveSlot;

            string freqText;
            if (state.FrequencyOverrides.TryGetValue(slot, out var dynFreq))
                freqText = $"{FormatFreq(dynFreq)} MHz · DIRECT";
            else if (state.Presets.TryGetValue(slot, out var ch) && _prototype.TryIndex(ch, out var proto))
                freqText = $"{FormatFreq(proto.Frequency)} MHz · {proto.LocalizedName.ToUpperInvariant()}";
            else
                freqText = "--- EMPTY ---";

            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 4 };

            // Select button (label + freq)
            var selectBtn = new Button
            {
                Text           = $"[{label}]  {freqText}",
                HorizontalExpand = true,
                Pressed        = isActive && online,
                Disabled       = !online,
            };
            var capturedSlot = slot;
            selectBtn.OnPressed += _ => OnSelectSlot?.Invoke(capturedSlot);

            // Tune button (opens slot entry panel)
            var tuneBtn = new Button
            {
                Text     = "TUNE",
                MinWidth = 52,
                Disabled = !online,
            };
            tuneBtn.OnPressed += _ => OpenSlotEntryPanel(capturedSlot, state);

            // Delete button
            var delBtn = new Button
            {
                Text     = "DEL",
                MinWidth = 44,
            };
            delBtn.OnPressed += _ => OnDeleteSlot?.Invoke(capturedSlot);

            row.AddChild(selectBtn);
            row.AddChild(tuneBtn);
            row.AddChild(delBtn);
            SlotListContainer.AddChild(row);
        }
    }

    // Slot entry panel

    private void OpenSlotEntryPanel(int slot, ANPRCRadioState state)
    {
        _entryTargetSlot = slot;
        var label = state.SlotLabels.TryGetValue(slot, out var lbl) ? lbl : $"P{slot + 1}";
        SlotEntryHeaderLabel.Text = $"TUNE [{label}]:";
        SlotEntryPanel.Visible    = true;
        EntryFreqLineEdit.Text    = string.Empty;
        ShowEntryTab(EntryTab.Freq);
        RebuildNetList(state);
    }

    private void CloseSlotEntryPanel()
    {
        SlotEntryPanel.Visible = false;
        _entryTargetSlot       = -1;
        EntryFreqLineEdit.Text = string.Empty;
    }

    private void ShowEntryTab(EntryTab tab)
    {
        _activeEntryTab        = tab;
        EntryFreqPanel.Visible = tab == EntryTab.Freq;
        EntryNetScroll.Visible = tab == EntryTab.Net;

        EntryTabFreqButton.Pressed = tab == EntryTab.Freq;
        EntryTabNetButton.Pressed  = tab == EntryTab.Net;
    }

    private void RebuildNetList(ANPRCRadioState state)
    {
        EntryNetList.RemoveAllChildren();

        var opFaction = state.OperatorFaction;

        foreach (var proto in _prototype.EnumeratePrototypes<RadioChannelPrototype>())
        {
            // Filter out sentinels and non-displayable channels.
            if (proto.Frequency <= 0)
                continue;

            // Only list the radio's own faction nets. Faction-less channels (colony,
            // civilian) are left out; those get tuned by raw frequency instead.
            if (!string.IsNullOrEmpty(opFaction) && proto.Faction != opFaction)
                continue;

            var capturedProto = proto;
            var btn = new Button
            {
                Text           = $"{proto.LocalizedName.ToUpperInvariant()}  —  {FormatFreq(proto.Frequency)} MHz",
                HorizontalExpand = true,
            };
            btn.OnPressed += _ =>
            {
                if (_entryTargetSlot < 0) return;
                OnSetSlotChannel?.Invoke(_entryTargetSlot, new ProtoId<RadioChannelPrototype>(capturedProto.ID));
                CloseSlotEntryPanel();
            };
            EntryNetList.AddChild(btn);
        }
    }

    // Net log

    private void RebuildNetLog(ANPRCRadioState state)
    {
        RebuildNetLogChannelFilter(state);

        NetLogContainer.RemoveAllChildren();

        var shown = 0;
        foreach (var entry in state.NetLog)
        {
            if (!NetLogEntryMatchesFilters(entry))
                continue;

            shown++;
            var ts = TimeSpan.FromSeconds(entry.Timestamp);
            var timeStr = $"{(int) ts.TotalMinutes:D2}:{ts.Seconds:D2}";

            var line = new Label
            {
                Text           = $"[{timeStr}] {entry.SenderName} · {entry.ChannelDisplay}",
                FontColorOverride = TextLog,
                ClipText       = true,
            };
            var msg = new Label
            {
                Text           = $"  {entry.Message}",
                FontColorOverride = TextDim,
                ClipText       = true,
            };
            NetLogContainer.AddChild(line);
            NetLogContainer.AddChild(msg);
        }

        var filtered = _netLogChannelFilter != null || _netLogSearchFilter.Length > 0;
        NetLogCountLabel.Text = filtered
            ? $"{shown}/{state.NetLog.Count} entries"
            : $"{state.NetLog.Count} entries";

        if (filtered && shown == 0 && state.NetLog.Count > 0)
        {
            NetLogContainer.AddChild(new Label
            {
                Text              = "NO ENTRIES MATCH FILTER",
                FontColorOverride = TextDim,
            });
        }
    }

    private bool NetLogEntryMatchesFilters(ANPRCNetLogEntry entry)
    {
        if (_netLogChannelFilter != null && entry.ChannelDisplay != _netLogChannelFilter)
            return false;

        return _netLogSearchFilter.Length == 0 ||
               entry.SenderName.Contains(_netLogSearchFilter, StringComparison.OrdinalIgnoreCase) ||
               entry.Message.Contains(_netLogSearchFilter, StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Keeps the channel dropdown in sync with the nets actually present in the log.
    /// Items are only rebuilt when that set changes, so an open dropdown isn't
    /// yanked shut by the periodic state updates.
    /// </summary>
    private void RebuildNetLogChannelFilter(ANPRCRadioState state)
    {
        var channels = state.NetLog
            .Select(e => e.ChannelDisplay)
            .Distinct()
            .OrderBy(c => c, StringComparer.OrdinalIgnoreCase)
            .ToList();

        if (channels.SequenceEqual(_netLogChannels))
            return;

        _netLogChannels.Clear();
        _netLogChannels.AddRange(channels);

        NetLogChannelFilter.Clear();
        NetLogChannelFilter.AddItem("ALL NETS", 0);
        for (var i = 0; i < _netLogChannels.Count; i++)
        {
            NetLogChannelFilter.AddItem(_netLogChannels[i], i + 1);
        }

        // Re-select the previously chosen net; if it rotated out of the log
        // (50-entry cap), fall back to ALL rather than filtering on a ghost.
        var selectedIdx = _netLogChannelFilter == null ? -1 : _netLogChannels.IndexOf(_netLogChannelFilter);
        if (selectedIdx < 0)
        {
            _netLogChannelFilter = null;
            NetLogChannelFilter.SelectId(0);
        }
        else
        {
            NetLogChannelFilter.SelectId(selectedIdx + 1);
        }
    }

    // Helpers

    private static string FormatFreq(int raw)
        => raw >= 1000 ? $"{raw / 1000}.{raw % 1000:D3}" : $"00.{raw:D3}";

    private static string BandName(int f)
        => f < 3000 ? "LF" : f < 30000 ? "HF" : f < 88000 ? "VHF" : f < 300000 ? "UHF" : "SHF";

    private static string Bars(int filled, int total)
    {
        filled = Math.Clamp(filled, 0, total);
        return new string('█', filled) + new string('░', total - filled);
    }

    private static string ModeShort(RadioMode m) => m switch
    {
        RadioMode.FrequencyHopping => "FH",
        RadioMode.SingleChannel    => "SC",
        RadioMode.CipherText       => "CT",
        RadioMode.PlainText        => "PT",
        _                          => "FH",
    };
}
